### ISSUE TITLE
Error at Defeat or Sell Gem?

### ISSUE THREAD

**Issue by dcloud102** [GkevinOD/msl-bot#13]
I don't know what to make of this error.  Please see screenshot.
![got this error](https://cloud.githubusercontent.com/assets/24919677/23471334/9a82ee80-fe6e-11e6-8031-05d5168839a3.JPG)

**Comment by GkevinOD** [comment]
This error comes from when the bot tried to sell a non-existing gem. The sellGem() function returns an array of the gem info, but since there was no gem no array was returned. The [6] element does not exist giving an error.

The bot may have mixed the 'defeat' location with 'battle-end-exp' thus going into the process of trying to sell the gem. I've added a condition to check if there was a gem, if not just skip the process.

To simply fix this error within that version, replace that if statement line of code with:

```
Local $gemInfo = sellGem("B" & $strGolem, $intSellGradeMin, True, 6, $intKeepGradeMinSub, $intMinSub)
If isArray($gemInfo) And StringInStr($gemInfo[6], "!") Then
    $intGoldPrediction += $intGoldEnergy
EndIf
```
