### ISSUE TITLE
Collecting Hourly Rewards Not Functional

### ISSUE THREAD

**Issue by dcloud102** [GkevinOD/msl-bot#14]
I did golem and then it goes to back to village and saw "Do you want to quit screen"  and close that and then went back to map and resume battle in golem.  My log says:

[18:38:38] Collecting hourly rewards..
[18:38:38] Could not recognize village position.
[18:38:57] Checking for guardian dungeons...
[18:39:12] Found dungeon, attacking x1.

Collecting hourly rewards is a cool feature.  Hopefully it works.  Is it a delay issue where the wait for the screen to load is not enough?

**Comment by GkevinOD** [comment]
From my experiences with the game so far, there are there are three views that the village falls into. In the code the bot has to know what which of the three position are to be able to find the locations of the hourly rewards. I used static images of the ship to indicate the position which is 3 images in the misc folder.

From what it looks like in your log, the images (misc-village-pos1, misc-village-pos2, misc-village-pos3) are not working. You can test that out by typing the image name when in the village (note: do not move the camera position from the initial position). 

Here's an image of what you should see if it finds the image:
![image](https://cloud.githubusercontent.com/assets/5211248/23491316/6bd32cc8-feb2-11e6-846d-3b54a3690b66.png)

If all three images do not work, then the problem might be in the code and not the images. Otherwise, you can send an image of your village (make sure you scratch out your name) and I'll help you then.

**Comment by GkevinOD** [comment]
Also you can test the hourly function by typing in the Test Code: 'getHourly()'

**Comment by dcloud102** [comment]
I've recaptured the images using the old 1.5 version.  Got the findImage to recognize the misc-village-pos1.  Then I ran the getHourly() code.  Got error message saying Could not recognize village position.  See image below.

![capture](https://cloud.githubusercontent.com/assets/24919677/23494077/022d14ae-fed6-11e6-9d1f-05731de04a74.JPG)

**Comment by GkevinOD** [comment]
Okay the problem should be the tolerance value I selected in the function. I'm not able to commit an update right now, but you can fix this by going into the functions folder -> village and you will find the getHourly.au3. You will 3 of the following code:

If isArray(findImage("misc-village-pos1")) Then

On each findImage(...) replace that with findImage(..., 50)

findImage("misc-village-pos1", 50)

The default tolerance is 10, but the findImage debug is at 50. That should fix the problem

**Comment by dcloud102** [comment]
Tested and the fix works.
