### ISSUE TITLE
Bot 1.8.0 Connection Lost Debug - Set Location bug

### ISSUE THREAD

**Issue by dcloud102** [GkevinOD/msl-bot#28]
I don't know if you are experiencing this or not, but I found a bug while trying to Set Location for Connection Lost.  I did the location test and it was unknown.  Then click Set Location and then typed in "lost-connection" and it did not register the new image.  Tried "lost_connection" and it crashed the program with error message.  

I think the prompt that list available text should be dashes rather than underscore.  At first, I was confused by it and had to verified the existing images.

**Comment by GkevinOD** [comment]
It is because inside the global.au3, there around 4 locations that I have not been able to encounter yet so they do not have a specified location and size. If you are able to find it again you can help me get the information by following this step:

Use Find Image: "location-connection-lost"
And tell me the Found and Size.

**Comment by dcloud102** [comment]
Here is the info based on my image capture:

Global $dim_lost_connection = "428,317,35,24"

**Comment by dcloud102** [comment]
Another thing I noticed while farming golem, that it detected quest complete and go back to collect quest.  Once finished collecting quest, it doesn't do anything.  I believe it is missing the code navigate("map") somewhere.

**Comment by GkevinOD** [comment]
I'll look into it, havent tested some of them so there may be buggy codes. I usually don't merge with master branch until they are stable enough. Anyways thanks for the feedback!
