### ISSUE TITLE
Bot Not Capturing Exotic

### ISSUE THREAD

**Issue by dcloud102** [GkevinOD/msl-bot#5]
Don't know why it's not recognizing exotic.  I can't seem to find the code in global.au3 

Global $imagesLegendary = ["catch-legendary", "catch-legendary2", "catch-legendary3", "catch-legendary4", "catch-legendary5"]
 -	Global $imagesRare = ["catch-rare", "catch-rare2", "catch-rare3"]
 -	Global $imagesSuperRare = ["catch-super-rare", "catch-super-rare2"]
 -	Global $imagesExotic = ["catch-exotic", "catch-exotic2", "catch-exotic3"]

the new code asks for $varImages but global.au3 doesn't have it.  Do we need to add 

Global $varImages = ["catch-exotic3", "catch-exotic", "catch-exotic2", "catch-legendary", "catch-legendary2", "catch-legendary3", "catch-legendary4", "catch-legendary5", "catch-variant", "catch-variant2", "catch-variant3", "catch-rare", "catch-rare2", "catch-rare3"]

**Comment by GkevinOD** [comment]
I changed it to make it easier to add images. All you need to do is have the image named capture_exotic#.bmp and it will automatically count it.

**Comment by dcloud102** [comment]
Oh, so all you need to do is us the _CaptureRegion method to get the new image and it should work with the new code?  Odd, I use the above code and added it to global.au3 and it worked without having to catch new images.  Also, should I report a new issue about catching astromon and running out of astrochip?  It's looping saying "An astromon has been found..."

**Comment by GkevinOD** [comment]
It's fine if you don't make another issue, I know how to fix the no astrochip loop thing.

Anyways, $varImages is a parameter for the function catch(), so having that global variable will basically do nothing since it will be overwritten by the passed in value of the parameter. However, there may be instances where the bot does not detect the astromon the first time and choose to skip or something. I'll have it double check so it doesn't skip any rares. 

To make sure though, all you need to do is use the _CaptureRegion() and have capture-[astromon][#].bmp and it should automatically after you restart the script.

**Comment by GkevinOD** [comment]
Fixed in v1.3.4 and above. Should be my last commit for today, unless I made a type or something which I'll fix real quick.
