### ISSUE TITLE
on farm gem mode issue

### ISSUE THREAD

**Issue by 593394978** [GkevinOD/msl-bot#70]
when meet the exotic, legendary , rare,  super rare , variant, will catch the slime first. 
the battle was no found the silme , the bot will kill sach as the exotic, legendary , super rare ,rare.

**Comment by Shimizoki** [comment]
As a clarification:

When running "Farm Astromon" the bot will prioritize rare astromons over the selected astromon, this is in contrast to "Farm Gem" which only catches the selected astromon and kills everything else.

Part of the reason for this is because 16 mons are caught in one go, but the bot does not yet distinguish rares from the selected mon. Once 16 mons are captured, you may actually end up with 15 of the selected mon, and 1 rare... which is not enough to complete an evo3.

Another part is that farming gems requires a minimum number (16) free spaces in the inventory, however if you start with 16 and then catch a rare, you will be left with only 15 spaces for the selected astromon. This will cause the evolution to fail, as the current logic is not designed to work in this regard

----

A proposed fix is to track catches separately such that the counter is only applied when catching the selected mon, and track the number of free spaces so the script can exit once it reaches an invalid state. (minimum 4 spaces required to evo2 a mon)
