### ISSUE TITLE
Custom image sliming for extreme and hard evolution problem

### ISSUE THREAD

**Issue by Arayalaa** [GkevinOD/msl-bot#90]
I tried to make a universal picture with just slime and that didnt work, was wandering why. Also why not just use the 1 star photo instead? Since only the slime there is 1 star.

Also after changing catch image to 1 star it just gets stuck in monster screen grid sorted by recent. Not sure if this is related or not have not tried slime normally.

EDIT: tested them to run with original option of "Slime" and it works, it would be nice if it works for extreme and hard though.

Options:
Gems to sell: 1, 2, 3
Usable Astrogem: 900
Guardian mode: Both
Target boss: Enabled
Collect quests: Enabled
Hourly script: Enabled
Finish round: Enabled
Gems to farm: 300
Difficulty: Extreme
Astromon: one star

In the image theres only 8 slimes cause I manually evolved them when the script did not work.

Nox version. Ex. version 5.0.0.1
Bot app version. Ex. version 3.9.0
Script that you used. Farm gem
A screenshot if possible. https://imgur.com/a/7Utk5

**Comment by gquito** [comment]
There are maps where there are more than one 'one-star' monster; however,  you are right that we should use the 1 star since most maps only have 1, so I'll probably change the default to "one star" instead of slime. 

Currently, the evolving process has some issues for some people that may cause the process from being stopped in the middle. Most of the issues that occur happen trying to recognize and find the slime icon, so there will be some updates to fix this issue in Farm Gem.
